; This is a configuration file contains all absolute paths

[PROCESSING_TOOL]
sandpro_dir = /home/daqtest/Processor/sandpro


[RUN_ANALYSIS]
data_dirs = /home/daqtest/DAQ/SandyAQ/softlink_to_data/all_data/
exclude_dirs = 
run_list_output_file = /home/daqtest/DAQ/SandyAQ_vera/SandyAQ/softlink_to_data/processed/run_info_single_channel_20250325.h5


[GAIN_ANALYSIS]
gain_list_input_file = /home/daqtest/DAQ/SandyAQ_vera/SandyAQ/softlink_to_data/processed/run_info_single_channel_20250325.h5
gain_list_output_file = /home/daqtest/DAQ/SandyAQ_vera/SandyAQ/softlink_to_data/processed/gain_info_single_channel.csv

