# all paths are relative to this folder
# !!!!!! important !!!!!!
# if added entries / edited the key name;
# please also edit common/config_reader.py

[CONFIG_PATHS]
data_taking_config = data_taking_config.ini
data_processing_config = data_processing_config.ini
absolute_path_config = absolute_path_config.ini

[PRIVATE_CONFIG_PATHS]
sandpro_process_config = internal/sandpro_process_config.json
tmp_process_config = internal/tmp_process_config.json
