[GAIN_PROCESSOR_SETTINGS]
# number of bins for the histogram (SPE calibration)
hist_n_bins = 200
# range for the histogram (SPE calibration)
hist_range = -0.1 10

[RUN_PROCESSOR_SETTINGS]
# if True, all the processed entries will be processed again
reprocess = False

# name of the key, needed for the hdf5 file. 
# Probably don't need to change. 
# Only here to make sure read in and read out 
# are reading the same key
hdf5_key = processed_data


[EVENT_PROCESSOR_SETTINGS]

# mode: "single_channel" or "all_channels" or a number which is the number
# of channels in sync
# mult-channel not implemented yet
mode = single_channel
# total no. of sample for the baseline calculation
n_baseline_samples = 120 
# no. of samples to average out for the baseline calculation
n_baseline_samples_avg = 40 

# no. of events to discard from the beginning of the list of all events:
# the first 1000 events are usually noisy and with higher baseline
# no need to change unless necessary 
truncate_event_front = 1000 
# no. of events to discard from the end of the list of all events
truncate_event_back = 500 

# from 0 to 1, of the record window, where to integrate for peak area
; integral_window_for_area = 0.3 0.55

[FIT_SPE_SETTINGS]

# threshold for the fit to be considered a good fit
# atm value found by eyes, not optimized
good_fit_threshold = 0.03

; guess for the SPE peak position for bias voltag at 45, 46, 47, 48, 49, 50, 51, 52 V
; values used to initialize the fit
spe_position_guess = 0.21 0.22 0.25 0.3 0.5 0.5 0.6 0.7 0.8
spe_bias_voltage = 44 45 46 47 48 49 50 51 52

# to convert the SPE peak position to gain
input_impedance_Ohm = 50
